### PR TITLE
Enable JPEG_SUPPORT (for TIFFs) and test

### LINKED ISSUE #101: Support for JPEG-compressed GeoTIFFs
It would be awesome if the pre-built binaries included support for JPEG-compressed GeoTIFFs.  As it stands now, `gdal` emits an opaque error: `Error: Error opening dataset`

### PR DESCRIPTION
**Pull request by mojodna**
Enables support for JPEG-compressed TIFFs using the bundled libjpeg.

Fixes #101

### CODE REVIEW

**Comment by mojodna** [comment]
Bump.

**Comment by brianreavis** [comment]
Ironic, I was just looking this over when you bumped. Appveyor seems to be failing... It looks like we'll need to bundle libjpeg in order to not break windows builds:
```
 tif_jpeg.c
..\..\..\..\deps\libgdal\gdal\frmts\gtiff\libtiff\tif_jpeg.c(88): fatal error C1083: Cannot open include file: 'jpeglib.h': No such file or directory [C:\projects\node-gdal\build\deps\libgdal\gyp-formats\libgdal_gtiff_frmt.vcxproj]
```

**Comment by mojodna** [comment]
;-)  Thanks!

Ah, Windows.  Sorry, wasn't able to test it out there.  libjpeg is included in the repo, so it sounds like it's a matter of adding it to the VC project?

**Comment by brianreavis** [comment]
Haha, no worries. It should be as simple as adding https://github.com/naturalatlas/node-gdal/tree/master/deps/libgdal/gdal/frmts/jpeg/libjpeg to the include directories in the gyp config. I can give it a look this evening. On mac/linux, it's probably pulling the system libjpeg headers.

**Comment by mojodna** [comment]
Ah, that makes sense.  Thanks for looking into it!!

**Comment by brianreavis** [comment]
No prob! [tilelive-raster](https://github.com/mojodna/tilelive-raster) looks like an awesome idea

**Comment by brianreavis** [comment]
@mojodna Good news – that did the trick :) A new version is out / now building: https://github.com/naturalatlas/node-gdal/releases/tag/v0.4.4. Thanks for these changes!

**Comment by mojodna** [comment]
Fantastic!  Thanks!!!

**Pull request merged**
