### PR TITLE
Update Node.js versions

### PR DESCRIPTION
**Pull request by jdesboeufs**
Drop all obsolete versions (4, 6, 8, 9)
Add current versions (12, 13)

Based on #259

### CODE REVIEW

**Comment by jdesboeufs** [comment]
Please @brianreavis @brandonreavis @springmeyer ;)
It's hard to be stuck to Node 10!

**Comment by jdesboeufs** [comment]
I published a module called `gdal-next`, with prebuilt addon for Linux and macOS (Node.js 12 only).

Sorry for that, but we have to go ahead.

**Comment by weagle08** [comment]
Thanks for this!

**Comment by wandergis** [comment]
I wish this will be merged soon.

**Comment by ezze** [comment]
@jdesboeufs, thanks for doing that!

Guys, please merge this PR. Node 12 is already the latest LTS.

**Comment by tempranova** [comment]
Any update here?

**Comment by jdesboeufs** [comment]
@tempranova We forked the repository
Look at https://github.com/contra/gdal-next

**Pull request merged**
