### PR TITLE
Node10 compatibility

### PR DESCRIPTION
**Pull request by Algunenano**
Adding Node10 to the matrices. Leaving 4 (out of support) and 9 (Maintenance) for now.

Needs package-lock.json update

### CODE REVIEW

**Comment by Algunenano** [comment]
Seems osx fails when building the shared libraries due to some failure in the setup, but it was failing before my changes too. Also the Windows builds are failing with node 10, but I'm not sure why.

As I don't use any of the platforms, any suggestion on how to deal with those failures is welcome.

**Comment by contra** [comment]
@Algunenano This works great for us btw - if only we could get the prebuilt files for node 10 working, the build from source is incredibly slow.

**Comment by Algunenano** [comment]
> I'll have to look into how that works in this project.

It uses node-pre-gyp to [upload them to aws when you add a commit with `[Publish binary]`](https://github.com/naturalatlas/node-gdal/blob/fd6398259b21e3aa47dc1058f3b5aa31cfcb46dc/.travis.yml#L68) but it's a PITA to set up since you need to fork the project, setup AWS and publish your own package in npm and adapt any package that depends on this to point to your new package (which usually means more forks).

Anyway, if the maintainers need anything extra to get this merged and published please let me know.

**Comment by contra** [comment]
```
../node_modules/nan/nan_maybe_43_inl.h:112:15: error: no member named
      'ForceSet' in 'v8::Object'
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
         ~~~  ^
../src/utils/fast_buffer.cpp:18:50: error: no matching member function for
      call to 'NewInstance'
        Local<Object> actualBuffer = bufferConstructor->NewInstance(3, con...
```

On node 10.5 FYI

We're forking this repo and do some prebuilds right now, I tried to email the maintainers and didn't receive any response for the last week so they either fell off a cliff (RIP) or really don't care.

**Comment by brianreavis** [comment]
> I tried to email the maintainers and didn't receive any response for the last week so they either fell off a cliff (RIP) or really don't care.

Please, let's not get petty. _Do care very much_, but just happen to be very busy. Vetting maintainers is a serious deal – node-gdal is used by many people, all of whom would not be very happy with us getting brazen with publish access to NPM. As for general help, we would indeed be super appreciative of it! I am sorry for not getting back to you sooner on that.

Given node's release cadence, latest non-LTS releases are sometimes a headache to keep up with. One of the reasons being the CI environment being slow and shaky. Getting builds to work across all platforms and node versions can be slow and tedious to get right. Sorting out these sorts of issues does not require maintainer privileges.

> hasn’t had a publish in 10 months

True and mildly unfortunate, but it's been stable?

---

Travis doesn't seem to be a blocker (runtime can fail without influencing the publishing of binaries). Node 10 support on Windows / AppVeyor _is_ a blocker, though.

```
LINK : fatal error LNK1194: cannot delay-load 'node.exe' due to import of data symbol '"__declspec(dllimport) const std::basic_ostream<char,struct std::char_traits<char> >::`vftable'" (__imp_??_7?$basic_ostream@DU?$char_traits@D@std@@@std@@6B@)'; link without /DELAYLOAD:node.exe [C:\projects\node-gdal\build\gdal.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:225:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\projects\\node-gdal\\lib\\binding\\node-v64-win32-ia32\\gdal.node" "--module_name=gdal" "--module_path=C:\\projects\\node-gdal\\lib\\binding\\node-v64-win32-ia32" "--napi_version=3" "--node_abi_napi=napi"
```

Not sure the fix off the top of my head and I haven't had time to dig into it.

Wholeheartedly appreciative of this PR and it looks great a glance. Thanks @Algunenano! Getting a release out with it integrated is not a simple push of a button until the Windows issue is fixed, though.

**Comment by contra** [comment]
Published our fork and prebuilds, you can just change `gdal` to `gdal2` and add this if a subdep needs to be overwritten:

```
"resolutions: {
  "gdal": "gdal2"
}
```

**Comment by contra** [comment]
@brianreavis I'm not trying to be petty - really just had no signal back at all, not sure you were still alive or what the deal was.

In the meantime, we got this PR built and working via a `gdal2` package to solve our own need, if anyone finds it helpful. We didn't have any windows issues - https://ci.appveyor.com/project/contra/node-gdal

**Comment by brianreavis** [comment]
image

Petty or passive aggressive – take your pick. Dude, this is what makes open-source suck. Please stop doing it. We're all on the same side here.

**Comment by contra** [comment]
@brianreavis Yeah, sorry - the wording was out of frustration. I felt like I reached out a ton and got nothing back so assumed you had totally ghosted the project and we needed to pick it up. I can collapse the fork once this is merged in, but we needed the prebuilds to fix our companies releases (build from source taking over 30mins).

**Comment by jdesboeufs** [comment]
It will be a huge work, but it’s time to work on a N-API version.
No more need to build against Windows/Mac, more releases.

Maybe it’s also time to switch to GDAL 2.3 🧐
Who’s in?

**Comment by Algunenano** [comment]
> Getting a release out with it integrated is not a simple push of a button until the Windows issue is fixed, though.

I'm having a look to try to have both the OSX and Windows builds fixed but both are OS that I don't normally use, so any help is appreciated.

**Comment by springmeyer** [comment]
> I'm having a look to try to have both the OSX and Windows builds fixed but both are OS that I don't normally use, so any help is appreciated.

@Algunenano thanks for pushing on this. I'm juggling a bunch of other upgrades (and trying to figure out N-API over at https://github.com/mapbox/node-sqlite3/pull/1008 /cc @jdesboeufs ) so I probably won't have time to push on this directly. But mention me if you get stuck on a compile error I can take a look.

**Comment by Algunenano** [comment]
I've made changes to all 3 platforms (linux had broken in the meantime too):
- Linux: Update to `trusty` to avoid not finding `libgdal1h`. I don't know where that package has gone, but I couldn't find it anymore in the ubuntugis-* repos for `precise`.
- OSX: Use the pre-installed gdal for the shared library build tests. This avoids some package conflicts that broke the build. Another option was to update everything (`brew upgrade`) but that brings PROJ 5.1 which fails in a couple of tests (also happens in Linux) and I didn't see any quick solution, so it needs investigating.
- Windows: Disabled win_delay_load_hook. Not sure if it will work, but that's all I got. If it doesn't I'm open to ideas, but I probably won't investigate further by myself.

**Comment by springmeyer** [comment]
Looking good. I propose this lands soon as `v0.9.7`.

> Linux: Update to trusty to avoid not finding libgdal1h

This seems reasonable to me - I'm also not sure what happened there. In my opinion it is the STATIC builds that really matter since those are what the binaries are published off of. So, I think we should only move the SHARED builds to `trusty`. If we keep the STATIC builds on precise they will stay using a compatible LIBC with centos 7, and older linux systems (without any drawback). So, keeping at `precise` for the STATIC jobs (by nesting the `dist` property per matrix job will avoid potentially breaking downstream users that are running on centos 7, etc.).

**Comment by Algunenano** [comment]
> So, keeping at precise for the STATIC jobs (by nesting the dist property per matrix job will avoid potentially breaking downstream users that are running on centos 7, etc.).

I couldn't find the proper way to do this (dist associated with certain envs) so I've declared all necessary builds explicitly.

**Comment by brianreavis** [comment]
Amazing work @Algunenano! This all looks good to go and everything is passing now ([appveyor](https://ci.appveyor.com/project/brianreavis/node-gdal/build/753), [travis](https://travis-ci.org/naturalatlas/node-gdal/builds/397370398)). I'll get this merged in and released this evening. Huge thanks for all your hard work on this.

**Comment by springmeyer** [comment]
Looks great - thanks @Algunenano. I think this is ready to merge. @brianreavis want to review and run out a release? Or would you be 👍 if I would (happy to)?

**Comment by springmeyer** [comment]
> Amazing work @Algunenano! This all looks good to go and everything is passing now (appveyor, travis). I'll get this merged in and released this evening. Huge thanks for all your hard work on this.

Whoops, I commented in a stale browser tab and did not see this before commenting. So, tag your-it @brianreavis for merging :)

**Comment by Algunenano** [comment]
Although I commented about it in the first post, I totally forgot about it: If still in use the `package-lock.json` needs to be updated. I didn't do it since in most of the projects with it they tend to prefer a specific `npm` release for consistency.

**Comment by brianreavis** [comment]
@springmeyer Any ideas on why this is saying the tar.gz already exists here https://ci.appveyor.com/project/brianreavis/node-gdal/build/756/job/8guyov91al5qmsmp? Can't seem to find a build that published it and it just seems to affect one target. Could be missing something!

Went ahead and published [0.9.7](https://www.npmjs.com/package/gdal/v/0.9.7). If it ends up being a problem, we can re-run/re-publish the build for Node 10 / 32-bit Windows.

**Comment by springmeyer** [comment]
> @springmeyer Any ideas on why this is saying the tar.gz already exists here https://ci.appveyor.com/project/brianreavis/node-gdal/build/756/job/8guyov91al5qmsmp? Can't seem to find a build that published it and it just seems to affect one target. Could be missing something!

I think what happened is that you published and then quickly tagged and the tag ran on appveyor too and the `[publish binary]` was in the commit message so two jobs ran:

screen shot 2018-06-29 at 12 58 13 pm

I think this is harmless but certainly confusing. I recently hit this and have been fiddling with https://github.com/mapbox/node-cpp-skel/pull/139 (but have not had time to test). There may be a cleaner way to avoid this, but the workaround is to ensure that you tag in a different commit than the one that ran `[publish binary]`.

**Pull request merged**
