### PR TITLE
Dep updates

### PR DESCRIPTION
**Pull request by springmeyer**
Solves #157 by upgrading gdal from 2.0.1 -> 2.0.2 and proj from 4.8.0- -> 4.9.2

Before merging:

 - [x]  Fix windows build problem `..\..\..\deps\libproj\proj\src\pj_strtod.c(79): fatal error C1021: invalid preprocessor command 'warning' [C:\projects\node-gdal\build\deps\libproj\libproj.vcxproj]`

### CODE REVIEW

**Comment by springmeyer** [comment]
Getting closer, now only node 4/5 builds are failing with:

```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\typeinfo(38): error C2504: 'exception': base class undefined [C:\projects\node-gdal\build\deps\libgeos\libgeos.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\typeinfo(42): error C2614: 'std::bad_cast': illegal member initialization: 'exception' is not a base or member [C:\projects\node-gdal\build\deps\libgeos\libgeos.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\typeinfo(59): error C2504: 'exception': base class undefined [C:\projects\node-gdal\build\deps\libgeos\libgeos.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\typeinfo(63): error C2614: 'std::bad_typeid': illegal member initialization: 'exception' is not a base or member [C:\projects\node-gdal\build\deps\libgeos\libgeos.vcxproj]
```

**Comment by springmeyer** [comment]
bfba79a did not take. It may be that both `_HAS_EXCEPTIONS=0` (inherited from node) and `_HAS_EXCEPTIONS=1` are set and the latter is not respected. Or `_HAS_EXCEPTIONS=1` is not set. It is taking > 2 hours until the jobs run/fail, so I think the ideal next step is for @BergWerkGIS to take the baton here and try debugging locally.

**Comment by brianreavis** [comment]
@springmeyer @BergWerkGIS Looks like undefining the variable did the trick ([build](https://ci.appveyor.com/project/brianreavis/node-gdal/build/641/job/ohhrb96uud3o3miy))

**Comment by springmeyer** [comment]
\o/ @brianreavis thank you!!

**Comment by brianreavis** [comment]
Kudos to @Brigadier1-9 over at https://github.com/creatale/node-dv/issues/33 for the idea!

**Comment by springmeyer** [comment]
Sweet, this being possible allows me to stop patching node for the c++11 builds I do (https://github.com/mapbox/node/commit/96310b04b78161b43ae3adf15e4644677834140f). /cc @BergWerkGIS 

Merging now!

**Pull request merged**
