### PR TITLE
Add io.js and drop node 0.11 in Travis CI env matrix

### PR DESCRIPTION
**Pull request by jdesboeufs**
Since node.js is now merging into io.js, we should run tests with latest io.js.
I also removed node.js 0.11 which is an "unstable" and abandonned branch.

Is it still necessary to run the TRUNK version on node.js 0.10?

Bye ;)

### CODE REVIEW

**Comment by jdesboeufs** [comment]
No changes which can explain the AppVeyor build failure...

**Comment by jdesboeufs** [comment]
Breaks with TRUNK or io.js 3.x.

**Comment by brianreavis** [comment]
Do we need io.js 1, 2, and 3, or can we just go with the latest? I'm hesitant to bloat build times. I feel like most people on io.js are aggressive version bumpers, but could be wrong. https://github.com/naturalatlas/node-gdal/blob/nan2.x/.travis.yml#L14-L15

**Comment by jdesboeufs** [comment]
io.js 3.x can be dropped since it's generally considered as node.js 4.0 alpha.
io.js 1.x is not very used, people switched quickly to 2.x

So we should keep:
- node.js 0.10 (legacy)
- node.js 0.12 (previous stable)
- io.js 2.x (major version, currently last supported by `node-gdal`)
- node.js 4.x

Considering multiple targets and multiple OS, I think we can focus on the last supported version.

**Comment by jdesboeufs** [comment]
Good job guys! ;)

**Pull request closed without merging**
