### PR TITLE
(WIP) update gdal, proj, geos, expat

### PR DESCRIPTION
**Pull request by contra**
@brianreavis @brandonreavis @springmeyer

This was a ton of work, and I haven't done a native module in a while so it took a lot of trial and error. Let me know if I messed anything up with the project structure.

Updates:

- GDAL to latest
- PROJ to latest
  - Has a hard dependency on sqlite, which it uses to store data now instead of using the file system - so a dependency for that was added. This should also make it easy to add GPKG support (#234).
  - Linking the build to use the generated `proj.db` file is a little funky, but should work fine. gyp doesn't have path expansion for defines, if you know a better way to do this we can change it easily.
  - User can still override the data dir via the PROJ_LIB env var
- GEOS to latest
- Expat to latest
  - High quality entropy warning disabled, since that doesn't expose itself in this module
- NAN + node-gyp + node-pre-gyp to latest
- Updated Buffer usage in tests to fix deprecation warnings
- Other misc dev deps

Project changes:

- Lots of files were being missed by the dependency cleanup scripts, so I fixed that and moved them to gitignore
- Updated gyp files to use the globbing utility wherever possible, to make updating easier in the future
- Removed algorithm patches because those landed upstream

Still TODO:

- `make test`: Handful of failing tests (9) around some coordinate transforms, possibly easy to fix
- `make test-shared`: 1 failing test for contourGenerate, no idea why that would be failing but need to check it out still
- Would like somebody to check out the changes in the src folder, I've tested it on both old (linking to shared on my local) and new versions (building from source) of GDAL so these changes should be fully backwards compatible. I'm not a C++ dev so feel free to rewrite those changes if I screwed it up.
- Test building on windows

Future improvements:

- Would be nice to keep the dep source code out of the repo, I saw a ticket from a few years ago where this was discussed so it seems like this was already planned. This PR was already a huge set of changes so I didn't want to rock the boat too much there.
- There's a lot of manual changes in the gdal format gyps, it would be nice if the update scripts intelligently merged changes in somehow
- Nan/V8 has a few new deprecation warnings that should get fixed

### CODE REVIEW

**Comment by jdesboeufs** [comment]
Great job!!

**Comment by springmeyer** [comment]
Yeah, excellent work on this @contra - thanks for the lift. Ping when it is ready for review. /cc @Algunenano might also be interested in helping review this.

**Comment by contra** [comment]
I could use a hand with the remaining items if any of them stick out as easy to anyone + reviewing the work so far before I hunker down and do the rest.

**Comment by contra** [comment]
Ping - is anyone willing/able to assist with getting this over the finish line?

**Comment by weagle08** [comment]
I can maybe help out as I've used this library in the past, but am not familiar at all with creating/updating native modules. You have a beginner level task to give me?

**Comment by contra** [comment]
I went ahead and updated all of the dependencies to latest again, made a few other enhancements, pulled in and merged the changes from #267 to fix the nan deprecations, and made some progress on the tests. There is only 1 failing test now - I think things are really close.

If one of the project maintainers could review this PR + help with the last failing test it would be great.

**Comment by porfirioribeiro** [comment]
Would be nice to have this updated!

**Comment by contra** [comment]
Quick update: Don't have the time to keep maintaining the PR and really needed these changes (and others) so decided to fork here: https://github.com/contra/node-gdal-next

I'm going to close this, but if the maintainers have interest in the future I would still love to contribute these changes back to the project.

**Pull request closed without merging**
