### PR TITLE
Enable BIGTIFF_SUPPORT

### PR DESCRIPTION
**Pull request by GretaCB**
@brandonreavis @brianreavis any chance I can be given access to merge this PR?

This PR adds the BIGTIFF_SUPPORT define to node-gdal. This was sparked from interest in processing bigger `tif` files, [particularly in `mapnik-omnivore`](https://github.com/mapbox/mapnik-omnivore/issues/55). The `gdal.open()` function was failing for BigTIFFs because the BIGTIFF_SUPPORT define was not included in the current node-gdal build.

cc @springmeyer

### CODE REVIEW

**Comment by brianreavis** [comment]
Awesome! We just need to disable the test when testing against shared GDAL that might not have it. Can you try adding this below? I just invited you to the team that has access to merging and such. Thought you were already on it – my bad
```
if (process.env.target !== 'SHARED') {
    describe('Open', function() { ... });
}
```

**Comment by GretaCB** [comment]
Sweet, thank you @brianreavis ! Also, where should I add the test above?

**Comment by brianreavis** [comment]
Oops, I worded that weirdly... just wrap what you have already in that if statement

**Comment by brianreavis** [comment]
PS. I had a typo: it should be `TARGET` not `target` (edited it to reflect that)

**Comment by brianreavis** [comment]
Looks like that did it! Just went ahead and merged it and released [0.4.1](https://github.com/naturalatlas/node-gdal/releases/tag/v0.4.1) so it's hopefully built by morning

**Comment by GretaCB** [comment]
:+1: thanks @brianreavis !

**Pull request merged**
